language: java

jdk:
  - openjdk14

sudo: false

install: true
script:
  - mvn install
services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE job4j_forum;" -U postgres

env:
  global:
    - CODECOV_TOKEN="525c307e-6ff8-4069-a107-cef83940f231"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - zubovvp@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always